name: Daily Evening Scripts

on:
  schedule:
    # Run Monday-Saturday at 10:02 PM ET (2:02 AM UTC next day)
    - cron: "2 2 * * 1-6"
    # Run Sunday at 6:02 PM ET (10:02 PM UTC)
    - cron: "2 22 * * 0"
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-evening-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "GROUPME_BOT_ID=${{ secrets.GROUPME_BOT_ID }}" >> $GITHUB_ENV
          echo "NYT_COOKIE=${{ secrets.NYT_COOKIE }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily evening scripts
        run: |
          python scripts/daily_evening_scripts.py
