name: Start Of Year Scripts

on:
  schedule:
    - cron: "0 12 1 1 *"
  workflow_dispatch: # Allows manual triggering

jobs:
  start-of-year-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "GROUPME_BOT_ID=${{ secrets.GROUPME_BOT_ID }}" >> $GITHUB_ENV
          echo "NYT_COOKIE=${{ secrets.NYT_COOKIE }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run start of year scripts
        run: |
          python scripts/start_of_year_scripts.py
