name: Start Of Month Scripts

on:
  schedule:
    - cron: "1 4 1 * *" # Run at 12:01 AM ET on the 1st of every month during DST
  workflow_dispatch: # Allows manual triggering

jobs:
  start-of-month-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start end of month scripts
        run: |
          python scripts/start_of_month_scripts.py
